name: infrastructure

services:
  postgres:
    image: postgres:16-alpine
    container_name: banking_db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=banking"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
      - "PGDATABASE=banking"
      - "PGUSER=user"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U user"]
      interval: 5s
      retries: 3
#    volumes:
#      - "./postgresql/data:/var/lib/postgresql/data"